name: secrets_of_szczecin_v2
description: "Secrets_of_Szczecin"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  equatable: ^2.0.5
  get_it: ^7.6.7
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_marker_popup: ^6.1.2
  flutter:
    sdk: flutter
  open_route_service: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
